<?php

/* http://www.loc.gov/standards/iso639-2/php/code_list.php */
return array(
	'English'                 => 'en',
	'Arabic'                  => 'ar',
	'Bengali'                 => 'bn',
	'Bulgarian'               => 'bg',
	'Catalan'                 => 'ca',
	'Chinese (Simplified)'    => 'zh-cn',
	'Chinese (Traditional)'   => 'zh-tw',
	'Croatian'                => 'hr',
	'Czech'                   => 'cs',
	'Danish'                  => 'da',
	'Dutch'                   => 'nl',
	/* 'English (UK)'            => 'en-GB', */
	/* 'English (US)'            => 'en', */
	'Estonian'                => 'et',
	'Filipino'                => 'fil',
	'Finnish'                 => 'fi',
	'French'                  => 'fr',
	/* 'French (Canadian)'       => 'fr-CA', */
	'German'                  => 'de',
	'Gujarati'                => 'gu',
	/* 'German (Austria)'        => 'de-at', */
	/* 'German (Switzerland)'    => 'de-CH', */
	'Greek'                   => 'el',
	'Hebrew'                  => 'he',
	'Hindi'                   => 'hi',
	'Hungarain'               => 'hu',
	'Indonesian'              => 'id',
	'Italian'                 => 'it',
	'Japanese'                => 'ja',
	'Kannada'                 => 'kn',
	'Korean'                  => 'ko',
	'Latvian'                 => 'lv',
	'Lithuanian'              => 'lt',
	'Malay'                   => 'ms',
	'Malayalam'               => 'ml',
	'Marathi'                 => 'mr',
	'Norwegian'               => 'no',
	'Persian'                 => 'fa',
	'Polish'                  => 'pl',
	'Portuguese'              => 'pt',
	/* 'Portuguese (Brazil)'     => 'pt-BR', */
	/* 'Portuguese (Portugal)'   => 'pt-PT', */
	'Romanian'                => 'ro',
	'Russian'                 => 'ru',
	'Serbian'                 => 'sr',
	'Slovak'                  => 'sk',
	'Slovenian'               => 'sl',
	'Spanish'                 => 'es',
	/* 'Spanish (Latin America)' => 'es-419', */
	'Swedish'                 => 'sv',
	'Tamil'                   => 'ta',
	'Telugu'                  => 'te',
	'Thai'                    => 'th',
	'Turkish'                 => 'tr',
	'Ukrainian'               => 'uk',
	'Urdu'                    => 'ur',
	'Vietnamese'              => 'vi'
);
